### ISSUE TITLE
Specifying custom rules.yaml in config.yaml not working

### ISSUE THREAD

**Issue by justinlittman** [webrecorder/pywb#176]
Steps to reproduce:
1. In config.yaml, specify a file for `domain_specific_rules`.
2. Add a custom rule to rules.yaml.
3. Test the rule.

Expected result:
Rule will work.

Actual result:
Default rules work.

I suspect the problem is because when RewriteContent in inited in ReplayView, the ds_rules_file kwarg is not provided.

**Comment by ikreymer** [comment]
This is now supported via `rules_file` config entry, eg: `rules_files: my_custom_rules.yaml`, but docs are needed. Tracking in #289
