### ISSUE TITLE
Frameless replay of captured websites?

### ISSUE THREAD

**Issue by fbuchinger** [webrecorder/pywb#210]
Hi,

I'm using pywb/wayback to replay some captured snapshots from web.archive.org. How can I get rid of the iframe into which the snapshot is injected? I want to take full-dimensional screenshots of the captured pages and the iframe complicates this matter quite a lot.

So far I tried to copy the UI templates to my collection folder and to adapt them (remove all the js-iframe injection/checks). But I wasn't successfuly - everytime I try to open the iframe src url in a new tab, the page gets framed again immediately.

Any hints?

**Comment by fkneist** [comment]
hi,

I had exactly the same problem and found a solution. If your collection is called "my_coll", you have to create and put a "config.yaml" into this folder: "./collections/my_coll", with the following content:

```
banner_html: "false"
framed_replay: false
```

**Comment by fbuchinger** [comment]
Thanks a lot @fkneist! The settings worked for me too and saved me from reverse-engineering the framing templates...

**Comment by seamang** [comment]
Thanks from me too! Can this information be added to the wiki or the README?

**Comment by ikreymer** [comment]
Sorry for taking long to respond.. That is a curious use of `banner_html` as its supposed to point to a jinja2 template file, but I see that `"false"` evaluates to a blank template.

I was thinking of removing the frameless replay in general in the next release, as inserting a banner without a frame is often problematic (dynamic pages can remove it), but I see that a frameless, banner-less replay is useful for automation/screenshots. Perhaps there should just be two modes?

- Framed replay with banner
- Frameless replay, with no banner

My other concern with frameless replay is that it may be used in a way that's deceiving users who think they're visiting a real site, though I suppose that's possible either way.

I am curious about everyone's use case here where you do not want a frame. I am looking to simplify and better document these options. Thanks!

**Comment by seamang** [comment]
@ikreymer My use case: using pywb to replay archived embeds (images mainly) within tweets harvested using the twitter API.

**Comment by fbuchinger** [comment]
@ikreymer our use case: running an [automated layout analysis script](https://github.com/fbuchinger/jquery.layoutstats)  on the archived snapshot. The frameless replay makes it much easier to inject the script and access its return values.

**Comment by ikreymer** [comment]
Frameless replay is fully available in pywb 2.0.0, see: http://pywb.readthedocs.io/en/latest/manual/configuring.html#framed-vs-frameless-replay
