### ISSUE TITLE
Tests fail if youtube-dl not installed

### ISSUE THREAD

**Issue by rebeccacremona** [webrecorder/pywb#270]
youtube-dl was made an optional dependency in https://github.com/ikreymer/pywb/commit/f0359877f083ad3985ebcb2e27cc6a08cdd6a17e, but presently, 4 tests require youtube-dl to be present: 

```
=========================================================== test session starts ===========================================================
platform darwin -- Python 3.6.3, pytest-3.3.1, py-1.5.2, pluggy-0.6.0 -- /Users/rcremona/.virtualenvs/pywb/bin/python
cachedir: .cache
rootdir: /Users/rcremona/code/pywb, inifile:
plugins: cov-2.5.1
collected 508 items 
....
pywb/recorder/test/test_recorder.py::TestRecorder::test_record_video_metadata FAILED
...
pywb/warcserver/test/test_handlers.py::TestBaseWarcServer::test_live_video_loader FAILED                                            [ 48%]
pywb/warcserver/test/test_handlers.py::TestBaseWarcServer::test_live_video_loader_post FAILED 
...
tests/test_live_rewriter.py::TestLiveRewriter::test_live_video_info FAILED
...
```

Possibly helpful points in history:
-  tests like this are skipped https://github.com/ikreymer/pywb/commit/f0359877f083ad3985ebcb2e27cc6a08cdd6a17e
-  tests like this mock the appropriate interface https://github.com/ikreymer/pywb/commit/080587516b312578da410b13ca6406d1ecaf5bbb
-  the mock is removed from `test_live_rewriter.py` https://github.com/ikreymer/pywb/commit/a4b770d34eca5760b132fe6a45d5aed93de794c8#diff-96acc3c52a0d4b8232c1150b221e0a13L8
-  It looks like in the great splicing of the two repos, additional tests were added that did not use a mock, but that particular history isn't that easy to reconstruct.

**Comment by ikreymer** [comment]
Thanks, should be fixed in 2.0.1, adding `importorskip` to all of the tests that require youtube-dl, an optional dependency.
