### ISSUE TITLE
Repeated filter parameters

### ISSUE THREAD

**Issue by thomaspreeceBBC** [webrecorder/pywb#284]
In the docs [https://pywb.readthedocs.io/en/develop/manual/cdxserver_api.html#filter](https://pywb.readthedocs.io/en/develop/manual/cdxserver_api.html#filter) it mentions that the filter parameter can be specified repeatedly. 
However after looking at the code the multiple filter parameters get compressed to just the last filter specified at `pywb/pywb/warcserver/basewarcserver.py` at line 63.
Is there currently a way to specify multiple filters?

**Comment by ikreymer** [comment]
Thanks for the report! Should work as expected now with multiple `filter=` args.
