### ISSUE TITLE
pywb cannot replay URLs that contain # in file names

### ISSUE THREAD

**Issue by despens** [webrecorder/pywb#290]
If a WARC file contains a URL that contains the character `#` in a file name, even when escaped as `%23`, pywb cannot find the resource.

This has is happening with a project @mucksmaeuschen is working on, please ask her for the WARC file.

**Comment by ikreymer** [comment]
Is this from "files" converted using `warcit`?

There is currently a test in place for replay of `%23` using `httpbin.org`:
```
live-rewrite-server
http://localhost:8090/live/http://httpbin.org/anything/test%23foo
```
Should display the request url as `"url": "http://httpbin.org/anything/test#foo"`

**Comment by mucksmaeuschen** [comment]
Hi Ilya - Thank you. Yes, the WARC-File was created with warcit. Should i send you the file?

**Comment by ikreymer** [comment]
Yes, you can attach it to this issue if its not too big, or send directly. Thanks!

**Comment by mucksmaeuschen** [comment]
[waste.warc.gz](https://github.com/webrecorder/pywb/files/1695856/waste.warc.gz)

**Comment by ikreymer** [comment]
Thanks, I think this is a bug in `warcit`, it needs to escape # -> %23 before writing to the WARC. Will track there.

**Comment by despens** [comment]
Confirmed, bug in warcit, see https://github.com/webrecorder/warcit/issues/5 

Closing here.
