### ISSUE TITLE
HTTPS certificates not available

### ISSUE THREAD

**Issue by despens** [webrecorder/pywb#291]
According to [pywb Documentation](http://pywb.readthedocs.io/en/latest/manual/configuring.html?highlight=certificate#https-proxy-and-pywb-certificate-authority), a certificate should be downloadable from http://wsgiprox/download/pem in proxy mode.

pywb output when accessing this URL:

```
::ffff:127.0.0.1 - - [2018-02-05 11:37:48] "GET http://wsgiprox/download/pem HTTP/1.1" 404 342 0.000309
```

**Comment by atomotic** [comment]
```
~ wb-manager init my-collection
~ wayback --proxy my-collection

~ curl -I -x localhost:8080 http://wsgiprox/download/pem
HTTP/1.1 200 OK
Content-Length: 2811
Content-Type: application/x-x509-ca-cert
Proxy-Connection: close
Date: Thu, 08 Feb 2018 13:31:40 GMT
```

is the pem file being created into the archive root?

```
├── collections
│   └── my-collection
│       ├── archive
│       ├── indexes
│       ├── static
│       └── templates
├── proxy-certs
│   └── pywb-ca.pem
```

**Comment by ikreymer** [comment]
@despens Did you start pywb with proxy mode enabled?, eg. by adding `proxy:` dict to the config or adding `--proxy` command line flag?

This url is only available when proxy mode is enabled in pywb, perhaps need to make the docs more clear.

**Comment by despens** [comment]
Indeed, with the proxy set to a collection it works. Rather a problem in docs. :) Will close here.
