### ISSUE TITLE
"Invalid HTTP methods in proxy mode" with garbled binary data

### ISSUE THREAD

**Issue by despens** [webrecorder/pywb#293]
When using a locally running pywb in proxy mode with FireFox 58, wayback output frequently contains lines like this one:

```
::ffff:127.0.0.1 - - [2018-02-05 11:56:50] "GET / HTTP/1.1" 200 310 0.006964
<gevent._socket3.socket object, fd=12, family=10, type=2049, proto=0>: Invalid HTTP method: '\x16\x03\x01\x00µ\x01\x00\x00±\x03\x03Ãp\x17\x1eÀú\x1c\x13¦\x1b¯V*¦¥Øçe´æ\x00sË\x01ló&Êr¸cf\x00\x00\x1eÀ+À/Ì©Ì¨À,À0À\n'
::ffff:127.0.0.1 - - [2018-02-05 11:57:01] "µ±ÃpÀú¦¯V*¦¥Øçe´æsËló&Êr¸cfÀ+À/Ì©Ì¨À,À0À" 400 - 0.000139
::ffff:127.0.0.1 - - [2018-02-05 11:57:01] "GET http://detectportal.firefox.com/success.txt HTTP/1.1" 404 342 0.000567
```

**Comment by ikreymer** [comment]
I believe this is debug logging from [wsgiprox](https://github.com/webrecorder/wsgiprox), enabled only when running with `--debug`? I am unable to repro this even with debug at the moment. Occasionally there are errors for a variety of reasons, browser resets connections, etc.. There are some improvements being made to `wsgiprox` also which may address some of these.

**Comment by ikreymer** [comment]
If it causes a particular issue, please reopen, closing for now.
