### ISSUE TITLE
Canonization issue with trailing slashes

### ISSUE THREAD

**Issue by despens** [webrecorder/pywb#295]
If a WARC file contains a URL with a trailing slash, like `http://1x-upon.com/~despens/`, but the user requests the URL without the trailing slash, like `http://1x-upon.com/~despens`, pywb will still replay the record with the URL containing the slash.

Many web server setups would create a 302 forward to the URL with a slash if appropriate (i.e., such a directory exists on a file-based server, or an unambiguous route would require this extra character). However, if this forward isn't part of the WARC, pywb shouldn't take any action and just present a not-found error when the URL without slash is requested for replay.

pywb replaying the resource under a wrong URL causes many issues with even simple pages:

- [URL with trailing slash](https://webrecorder.io/despens/canonisation-test/20180207115730/http://1x-upon.com/~despens/)
- [URL without trailing slash](https://webrecorder.io/despens/canonisation-test/20180207115730/http://1x-upon.com/~despens)

**Comment by ikreymer** [comment]
Issue better explained in #344, fixed by #346
