### ISSUE TITLE
wayback: empty reply from the server, and debug option does not help

### ISSUE THREAD

**Issue by dportabella** [webrecorder/pywb#298]
I've read the instructions on how to use and configure wayback:
https://pywb.readthedocs.io/en/latest/manual/apps.html#cli-wayback
https://pywb.readthedocs.io/en/latest/manual/configuring.html#configuring-pywb

However, wayback returns an empty page, and the debug option does not provide any hint. What can be the problem?

I have the current directory structure:
```
./config.yaml
./collections/one/archives/epfl_ch-20180220152925.warc.gz
./collections/one/indexes/epfl_ch-20180220152925.cdx.gz
```

./config.yaml is an empty file (using default values); and the warc and cdx files were created with https://github.com/helgeho/Web2Warc

```
$ wayback --debug
2018-02-20 15:38:02,368: [DEBUG]: Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
2018-02-20 15:38:02,368: [DEBUG]: Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
2018-02-20 15:38:02,686: [INFO]: Starting Gevent Server on 8080
2018-02-20 15:38:02,686: [DEBUG]: starting server on 63726

$ curl "http://localhost:8080"
curl: (52) Empty reply from server

$ curl "http://localhost:62369"
{"/<path_param_value>": {"modes": ["list_sources", "index", "resource"]}, "/<path_param_value>/postreq": {"modes": ["list_sources", "index", "resource"]}}
```

**Comment by ikreymer** [comment]
Based on the reply, it seems the request is not actually reaching wayback on 8080. Could there be something else running on that port perhaps? Is there any difference if you run on a different port, eg. `wayback -p 8081`?

(The warcserver port is picked automatically for internal use and requires using the Warcserver api, you don't need to connect to it directly)

The other issue is that the the cdx file needs to be decompressed, currently `.cdx.gz` is not supported, so that will also be a problem, but you can just decompress it into a plain `.cdx` file.

**Comment by dportabella** [comment]
These two things solved my problem, thx! It would be good to add an error message for both cases.

**Comment by ikreymer** [comment]
In the case of the port issue, was this an issue with Docker by any chance? 
Generally, there should be an error if a port is already taken, however, I've seen this with Docker on OSX, where a Docker container is mapped to a port on the host, and then a non-Docker service attempts to run on that same port, and there is no error that the port is already taken.. Have run into this a number of times, will look for a fix.

**Comment by dportabella** [comment]
It seems so. I tried running wayback on my OSX (without docker), and then run a second instance again on  my OSX (without docker), and it indeed reports the "address already in use" error.
the problem was that I had a docker process running using the 8080 port (that I didn't know, because i was not using that port), and wayback does not complain about this port already been used by docker.
