### ISSUE TITLE
Running wayback behind a reverse proxy + https

### ISSUE THREAD

**Issue by bricas** [webrecorder/pywb#314]
Is it possible to run wayback behind a reverse proxy that does https?

This is basically how our Kubernetes setup works, but my initial attempts didn't work right as it always wanted to push back a non-https url for assets and links.

Has this changed in 2.x release?

I believe I could probably deploy it using uwsgi w/ ssl suuport, but the app shouldn't need to be deployed with ssl directly.

**Comment by ikreymer** [comment]
pywb uses the WSGI standard `wsgi.url_scheme` variable to determine the scheme, so if that's set to `https`, it should work

 If you're deploying with nginx and uwsgi and having nginx handle ssl, this can be done by adding the `UWSGI_SCHEME $scheme` param, eg, if pywb is running in uwsgi on port :8081, a config might be as follows:

```
    location / {
        include uwsgi_params;

        uwsgi_param UWSGI_SCHEME $scheme;
        uwsgi_pass localhost:8081;
    }
```

Hope this helps, I'm not sure if this is sufficient for Kubernetes, but would be curious to know. Perhaps should also be added to the pywb docs.

**Comment by bricas** [comment]
I can confirm that if i switch from just `wayback` to `uwsgi uwsgi.ini` and add `nginx` on top using your sample config, i can get https urls returned.

This is not quite as trivial as I would've hoped (somehow getting `wayback` to return https urls via config or env variable) -- but it works.

**Comment by ikreymer** [comment]
Ok, I've added a config setting you can use: `force_scheme: https` which will force the rewriting to use https with the standard `wayback` deployment. For production deployment, nginx + uwsgi is still the recommended.

**Comment by bricas** [comment]
Thanks for the quick turn-around on this! Works great -- Thanks!

**Comment by ikreymer** [comment]
@bricas Just wondering, would specifying the scheme via  [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) or new [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) headers, which are a bit more standard, work for your use case, or is the `force_scheme: https` still the best option?

**Comment by bricas** [comment]
@ikreymer I believe our k8s setup sends the appropriate X-Forwarded-Proto header. So that would be the ideal, zero-config solution.

The force_scheme option is brute force, but works.

**Comment by ikreymer** [comment]
Great! Adding support for the `X-Forwarded-Proto` in #395 and deprecating `force_scheme` in next release.

**Comment by bricas** [comment]
@ikreymer FYI. I deployed 2.1.0 this morning, removed the force_scheme option, and everything still works as expected. Thanks!
