### ISSUE TITLE
GUI not rendering properly in the Safari browser

### ISSUE THREAD

**Issue by peterk** [webrecorder/pywb#393]
## Describe the bug
Opening a recorded URL in pywb wayback should show a hierarchical calendar. It displays correctly in Chrome but in Safari it looks like this:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/19284/47268384-84634b80-d550-11e8-814c-ba6b6e35778b.png">

This makes it impossible to see the date dropdown elements.

## Steps to reproduce the bug
Open a recorded URL in pywv wayback in Safari Version 12.0 (14606.1.36.1.9)

## Expected behavior
Expected UI to look like this:

<img width="985" alt="image" src="https://user-images.githubusercontent.com/19284/47268419-0c495580-d551-11e8-85f8-cf1d4bd9c62d.png">

## Environment

- OS: OSX Mojave
- Browser Safari 12.0 (14606.1.36.1.9)
- pywb==2.0.4
- Python 3.6.3

**Comment by ikreymer** [comment]
I'm unable to repro this issue with same version of Safari and OSX Mojave.
Can you confirm that you're using the standard pywb UI without any additional static content?
Using a different version of `bootstrap.min.js` can cause this issue, for example.

**Comment by machawk1** [comment]
I tried to reproduce this as well without avail on the same version of macOS, Safari, and pywb but Python 3.6.6 using Docker. The calendar displays identically in Chrome 70.0 and Safari 12.0:

<img width="1280" alt="screen shot 2018-10-22 at 9 47 13 pm" src="https://user-images.githubusercontent.com/2514780/47329829-15671f00-d644-11e8-9e82-432f12bfab8b.png">

I also tried it with the WARC @peterk provided in https://github.com/N0taN3rd/Squidwarc/issues/32 
 (after renaming to not include a `!` in the filename) with identical expected results per above (i.e., both browsers show calendar).

**Comment by peterk** [comment]
Restarted my computer, cleared cache and tried it from scratch and now I am unable to reproduce the error too. Sorry to bother you all. (But I saw it with my own eyes!! :-) )
