### ISSUE TITLE
The wiki of this repository contains outdated, misleading information

### ISSUE THREAD

**Issue by funkyfuture** [webrecorder/pywb#405]
## Describe the bug

there are seemingly outdated docs in  the wiki of this repository. it took me a while to figure out that [the page about proxy mode](https://github.com/webrecorder/pywb/wiki/Pywb-Proxy-Mode-Usage) contains an option name that is neither recognized by `pywb` nor yields a warning about invalid config contents.

**Comment by ikreymer** [comment]
Sorry about that, and thanks for reporting this! Updated the wiki to indicate the documentation is legacy and the latest docs is to be found at: https://pywb.readthedocs.io/en/latest/manual/configuring.html#http-s-proxy-mode
