### ISSUE TITLE
Auto-fetch worker in proxy mode may need to fetch directly through pywb 

### ISSUE THREAD

**Issue by N0taN3rd** [webrecorder/pywb#412]
In proxy mode the worker may not be able to fetch the URL due to CSP. If this is a prevelant the case will need to route it through recording (can confirm this is happening for some cdns ah la fonts.google). 

Double check non-proxy

**Comment by ikreymer** [comment]
@N0taN3rd this has been addressed with latest fixes to auto-fetch with the special fetch endpoint, right?

**Comment by N0taN3rd** [comment]
@ikreymer yes it has
