### ISSUE TITLE
WARCs of text files on web are indexed but not replayable.

### ISSUE THREAD

**Issue by machawk1** [webrecorder/pywb#42]
Uploaded WARCs containing captured of pages with only text are indexed with the URIs properly extracted but I receive a sad face icon (see below screenshot) when webrecorder tries to replay the content. This occurs both when the WARC is uploaded or placed somewhere on the web and webrecorder is given the URI.

Example WARC:
http://matkelly.com/temp/20140811154106173.warc

Validity verified:
./jwattools.sh test -e ./20140811154106173.warc
sh cdx-indexer ./20140811154106173.warc

Screenshot:
![screen shot 2014-08-11 at 11 47 48 am](https://cloud.githubusercontent.com/assets/2514780/3878394/e253c4d0-216e-11e4-9265-aed64f405751.png)

/cc @phonedude

**Comment by wumpus** [comment]
Damnit this bug convinced me that my warc writer is doing it all wrong! Good thing I didn't do too much crawling with it broken.

**Comment by anjackson** [comment]
FWIW we're currently storing the 'on ready DOM' as a separate WARC `resource` record under an augmented `WARC-Target-URI` e.g. `onreadydom:http://crawl-test-site.webarchive.org.uk/`. We do the same with screenshots/thumbnails/etc.

These get CDX-indexed so they are retrievable in principle, but we've not actually done much with them yet!
