### ISSUE TITLE
wb-manager errors on open-wayback excludes.txt conversion to pywb .aclj format

### ISSUE THREAD

**Issue by GilHoggarth** [webrecorder/pywb#439]
## Describe the bug
I'm wanting to convert an open-wayback excludes.txt file into the pywb .aclj format, using the wb-manager cmdline instruction as stated on https://github.com/ukwa/ukwa-pywb/blob/master/docs/access_controls.md#managing-access-lists. However, wb-manager is responding with:
```
usage: wb-manager [-h]
                  {init,list,add,reindex,index,metadata,template,cdx-convert,autoindex}
                  ...
wb-manager: error: argument type: invalid choice: 'acl' (choose from 'init', 'list', 'add', 'reindex', 'index', 'metadata', 'template', 'cdx-convert', 'autoindex')
```

## Steps to reproduce the bug
```
# virtualenv --version
15.1.0
# virtualenv -p /usr/local/bin/python2.7 venv
# source venv/bin/activate
# pip --version
pip 19.0.1 from /root/_o/wb-manager/venv/lib/python2.7/site-packages/pip (python 2.7)
# pip install pywb==0.33.0
# wb-manager acl importtxt ./z.aclj /root/gitlab/discovery_supervisor/twang/oukwa-wayback-config/exclude-blacklist.txt exclude
```

Or,
```
# virtualenv -p /usr/local/bin/python3.6 venv
# source venv/bin/activate
# pip --version
pip 19.0.1 from /root/_o/wb-manager/venv/lib/python3.6/site-packages/pip (python 3.6)
# wb-manager acl importtxt ./z.aclj /root/gitlab/discovery_supervisor/twang/oukwa-wayback-config/exclude-blacklist.txt exclude
```

## Expected behavior
As I've not got this to work so far, I'm assuming that I'll gain a ./z.aclj file with the open-wayback data formatted correctly for pywb.

## Screenshots
N/A

## Environment
RHEL7.6, virtualenv 15.1.0, python2.7.11 and python3.6.7

**Comment by anjackson** [comment]
Ah, so the acl functionality is only on the https://github.com/ukwa/pywb fork at the moment - you need to install that for it to work.

**Comment by ikreymer** [comment]
Yes, that's correct, sorry for any confusion. The plan is to merge that fork into the mainline pywb in an upcoming release.

**Comment by GilHoggarth** [comment]
Closing the issue then as it's not accurate in this case.
