### ISSUE TITLE
Possibility to define access date for proxy mode

### ISSUE THREAD

**Issue by despens** [webrecorder/pywb#452]
When accessing a collection via proxy mode, it is not possible to set a desired date.

Proposed solution: offer a command line switch to start pywb with a default access date for proxy mode, for instance `wayback --proxy-dt 200507241832`

This would make pywb usable for creating  software and network environments that are set to a certain time. Concrete context: in the software preservation context, legacy software accesses web resources that aren't available anymore and would be displayed inside the software. The software wouldn't respect system-wide proxy settings and not allow local proxy settings. Web traffic could be routed through pywb via a transparent proxy, providing a curated collection of for example online instruction manuals, plus fallback to public web archives with the default access time set to the release date or usage date of the software.

One pywb instance would be launched per software environment, with only a single collection defined, so the default date time could be set globally.

**Comment by ikreymer** [comment]
Supporting via:
`wayback --proxy my-archive --proxy-timestamp 20190201010203` can also be ISO date:
`wayback --proxy my-archive --proxy-timestamp 2019-02-01T01:02:03`

or set in `config.yaml`

```
proxy:
  coll: my-archive
  timestamp: 2019-02-01T01:02:03
```

**Comment by ikreymer** [comment]
Released in pywb 2.2.20190311
