### ISSUE TITLE
Recording fails to render

### ISSUE THREAD

**Issue by edsu** [webrecorder/pywb#459]
I suspect you already know about web content that fails to capture, but in case this one is new: https://www.newblackmaninexile.net/ ... it seems to capture when recording, but if you go to the recording later it fails to render. I tried downloading the WARC file and playing back, and the same thing happens.

**Comment by ikreymer** [comment]
@edsu thanks! Turned out to be a simple fix, I think.. (moved the issue from Webrecorder repo) 
The JSONP rewriter was too strict with comment.. Should be fixed in the associated PR if you want to try.
