### ISSUE TITLE
Failed playback due to encoding issue in modern pywb, not in v0.32.0

### ISSUE THREAD

**Issue by rebeccacremona** [webrecorder/pywb#471]
## In Brief

A website's javascript once made a poorly-formed AJAX POST, which was captured in the [attached warc](https://github.com/webrecorder/pywb/files/3237463/QSQ2-SJ6L.warc.gz). The warc can be played back without problems using pywb 0.32.0, but not with modern pywb (or Webrecorder/ Webrecorder Desktop app)

## At Length

Perma once captured https://www.wired.com/story/our-machines-now-have-knowledge-well-never-understand/, producing [this warc](https://github.com/webrecorder/pywb/files/3237463/QSQ2-SJ6L.warc.gz). The warc contains a peculiar POST request: it claims `content-type: application/x-www-form-urlencoded` in its headers, but the data it posted is not in fact a url-encoded string:
```
# output produced using warcio
# print(record.raw_stream.read())
# print(record.http_headers)

POST /?T=B&u=https%3A%2F%2Fwww.wired.com%2Fstory%2Four-machines-now-have-knowledge-well-never-understand%2F&t=1514932476678&v=1514932476802&Q=1&m=1 HTTP/1.1
origin: https://www.wired.com
content-length: 396
accept-language: en-US,*
accept-encoding: gzip, deflate
host: wired-app.quantummetric.com
accept: */*
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.37 Safari/537.36
referer: https://www.wired.com/story/our-machines-now-have-knowledge-well-never-understand/
cookie: __cfduid=dd3cdc36c20f0ddb575b25d041573c7671514932471
content-type: application/x-www-form-urlencoded

b'\x816l`L\xa04P\x0e\xe0r\x02\xb5\x89\x19\x00fP\xdb\x0e\xb0\x02,\xee\x0e\x04\x99\xc1\xc5*\x8c\x00\'\xd9\xa1IY\x95\xd0\xb4\xd8\xa6\x94}\x86\x0b@\xc2$\x86\xc9\xb4\x8b\xc0\xbc\x8c\t\x04Wj\xc0\x8a\x1a\xbdB\xf5#\x80\x0fC\t2%a\x1c\x1e\xec\x0c\x05\xa0F\xc2\x12U\xc84\xc8L\x88TX\xb6\x05\xb4"\xf3\xabB\x10\x1aj\xe5\x19\x0b\xa3\xd3!\xc8\x8b\x90@\xe1 `\x84`C\xc2h\x81\x90\xf3i\x11\x11@\xe9p\x0b\xb9\x91\xf0Q@\x81#k\xa0%\xb1a\xb8A\xa5\xd0Xg\x14\xc6$\xab\xd2\xf0H\x8as\xd6\xd3!\x91\xfar\xe2fV\x80!i\x90\x9a\x80\x0bCqXc\xd1t0&5\x91AR\xa6\xb9\x0fd#\xd3\xeaGtL\xe4X\xc6\xa9C\xf0\x0eB\xbb&c\xb0\xc4\x80\xe5\x1ap\n\xc3\x98\x10\xe0!d)h"\xd0\xc0N\x11\x08\xe8\x0b]R\x1c@-C\xc6\x1c\x98\xd4\\\xa9 <\xcds&\xce\xc3\xb1T\xac\x1d8@\x0c\xc2S \xe5n\xbc\x15\xa2\x8b\xce\xdc!\xd8\xe8\xa1O\xcf\x00\x81!\xa0\xa0*\x98\x01G\x86\x0b4\xc9\x04\xb0\xb8\x1aj\x92r\x05\xac3(\xe4\x18\x81\xf7\xcd\xc4d;1+lA\x9e\xc2\xd4\xa0\x90\t\x90\tW\x83\xac\xb1r\xfa\x08N \xaf\x80\xfa\x05\x84\x19x\xe3\x1cz\x87\xc5\xed\x80\xf84\xabb\xe5\x1f5O\x9c\xb9I\x9a\x9c5\xc0!\x89\x80\n\xd2\xa3OI\x93\x82\x93\x98\x10\x15\xae\x16=\x11\x88\xe9\x151\xb6\x1a\x08\xc8\n@c\x188\x0eo\x83\x82B\x11\x80J\xba\x00\x00@'
```
In the process of uploading this warc to Webrecorder, pywb attempts to [convert that data to a native string](https://github.com/webrecorder/pywb/blob/master/pywb/warcserver/inputrequest.py#L232), using the [utility function from warcio](https://github.com/webrecorder/warcio/blob/master/warcio/utils.py#L14), which attempts to decode using 'utf-8'. The decode move fails with a unicode error, of course... which causes upload to fail and playback to fail.

Perma has successfully been playing back this warc since the data of its creation because we've been using version 0.32.0 of pywb, which [decodes as 'iso-8859-1' instead of 'utf-8'](https://github.com/webrecorder/pywb/blob/0.32.0/pywb/utils/loaders.py#L59)...producing gobbledygook output here, but NOT an encoding error.

## Ideas?

I'm not sure what the right way to handle this is. Maybe, similar to [here](https://github.com/webrecorder/pywb/commit/adf34cdb3569ac3f5999cb8b07ff98f8ede168c1), this [whole stanza of code](https://github.com/webrecorder/pywb/blob/master/pywb/warcserver/inputrequest.py#L231-L257) should catch encoding errors, and base64 encode the query if anything goes wrong, like in the [`else`](https://github.com/webrecorder/pywb/blob/master/pywb/warcserver/inputrequest.py#L259)?

I am happy to submit a PR using this strategy, or any strategy you think might be better, for working around the issue.

**Comment by N0taN3rd** [comment]
@rebeccacremona thanks for opening this issue. 

I believe the simplest way for handling this case is as you pointed out

> Maybe, similar to [here](https://github.com/webrecorder/pywb/commit/adf34cdb3569ac3f5999cb8b07ff98f8ede168c1) 

which is to catch the exception and switch the encoding used by `to_native_str` to `iso-8859-1`.

Thoughts @ikreymer?

Please feel free to open a PR with a fix and if anything needs tweaking we can iterate from there.
