### ISSUE TITLE
Poorer replay quality than IA wayback (same resources!)

### ISSUE THREAD

**Issue by danielbicho** [webrecorder/pywb#527]
## Expected behavior
While replaying this page https://arquivo.pt/wayback/20080106005803/http://www.ojogo.pt/ we get poorer replay quality than https://web.archive.org/web/20080106005803/http://www.ojogo.pt/ even though is the same collection.

Maybe worth to checkout the difference from pywb and whatever wayback IA is using.

pywb image using memento endpoint to IA:
![image](https://user-images.githubusercontent.com/13105310/70814873-46fcf580-1dc4-11ea-8dc6-c468438a9eea.png)

IA wayback with the same page:
![image](https://user-images.githubusercontent.com/13105310/70814879-4bc1a980-1dc4-11ea-8757-679fc5cd9dc6.png)

**Comment by dubiouscript** [comment]
which pywb ?

source or some kind pk pkgmgr ??

**Comment by danielbicho** [comment]
pywb versions 2+, didn't try with the oldest versions

**Comment by edsu** [comment]
I don't know if it's related, but I noticed that the aquivo.pt version throws a JavaScript error `ReferenceError: addthis_share is not defined` whereas the archive.org does not. Could that be interfering somehow?

**Comment by danielbicho** [comment]
Thx for pointing out!! 

Doesn't seem related is just a error in our interface.
No frame version https://arquivo.pt/noFrame/replay/20080106005803/http://www.ojogo.pt/

Also the test above was performed using only pywb with Internet Archive Memento endpoint! No Arquivo.pt infrastructure/resources or customizations

**Comment by edsu** [comment]
Just fyi, that throws another JavaScript error:

    ReferenceError: WRP_SECTION is not defined

Could JavaScript errors be preventing wombat from running correctly?

**Comment by ikreymer** [comment]
This was a tricky one! Turns out this error (and others) are not related, but had to do with the `document.write` override in wombat. Should have a fix shortly.

**Comment by ikreymer** [comment]
@danielbicho the fix has been merged into develop. Please re-open if the issue persists with the latest, otherwise should be in the next full release!

**Comment by danielbicho** [comment]
Thank you @ikreymer. perfect! 
Tested the f0b9d5b commit, the last commit (93ce4f6) is breaking pywb

**Comment by ikreymer** [comment]
@danielbicho  what is the issue are you having with the latest commit? Do you want to open a new issue?

**Comment by danielbicho** [comment]
@ikreymer something breaks with our pywb framed version (custom template). I didn't have time to properly evaluate the issue. Will open a new issue if needed.
