### ISSUE TITLE
pywb versions ??

### ISSUE THREAD

**Issue by dubiouscript** [webrecorder/pywb#528]
https://github.com/webrecorder/pywb/releases
>latest :  on Nov 11, 2019  -  v-2.4.0-rc2  -  0d819aa

https://pypi.org/project/pywb/#files
>latest : pywb-2.3.5-py2.py3-none-any.whl

pywb-2.3.5.tar.gz   (2.6 MB) | Source | None | Aug 29, 2019
https://files.pythonhosted.org/packages/e7/5c/bdbded115cfa9b868e46c85c86dfca7677e4bfbbe68061a0d172e31615e2/pywb-2.3.5-py2.py3-none-any.whl

~who builds the github.com/releases ?~

~who builds pypi.org/project/pywb/ ?~ (Author: Ilya Kreymer )

why is pypi.org packaged                   version 2.3.5 at Aug 29, 2019 
but 
the github.com packaged / released  version v-2.4.0-rc2 at Nov 11, 2019

what *IS* the latest version ?.... i should use to build a pkg for my distro ???!!!!
=S

update =], ftr i found: https://github.com/webrecorder/pywb/pull/503

this: version / release numbering accurately/coherently
should (imho) help a little in answering questions like 
this one https://github.com/webrecorder/pywb/issues/527

...idk
perhaps this is common 
>LINE:64 2.1.0 was not tagged but pywb-2.1.0.tar.gz in PyPi was based on this commit
https://github.com/NixOS/nixpkgs/pull/52814/files#diff-9d5cad0a8dafcc5235e5b967f2778c2d

**Comment by ikreymer** [comment]
The latest full release has been 2.3.5.
The next upcoming release is 2.4.0-rc2, on the develop branch, is currently in testing.
There's been *a lot* of changes for 2.4, so haven't pushed it out yet.
Have been delayed due to holidays, other work, etc..
Do you have a suggestion for how to make the versioning better?
I suppose could push the RC candidates to pypi as well..

**Comment by ikreymer** [comment]
Closing for now, plz re-open if you have additional questions.

**Comment by dubiouscript** [comment]
hi ! ikreymer 
& thanks for the : Archiving Tools for All!! 

>Do you have a suggestion for how to make the versioning better?

unfortunately *afaik* i personally do not! .. have much insight about that
just a general sense im often found tracking sneaky goalpost/version badgers  !
https://github.com/zerodevx/zero-md/issues/19#issuecomment-546584861

...i had along list of prerequisites from requirements.txt ect(ect(ect))
to pkg before i got to the top of the dep tree (pywb)

and tbh im not all that adept in the python/packaging ecosystem 
just poking about trying / breaking things until they *hopefully* work =]
 usually while in some unusual configured env/system


>The latest full release has been 2.3.5.
>The next upcoming release is 2.4.0-rc2, on the develop branch, is currently in testing.
ah! thanks for the clarification

... wrt : "versioning better"/pkging ect 

guix/nix and software heritage ppl probably have think some thunks about this 
https://guix.gnu.org/blog/2019/connecting-reproducible-deployment-to-a-long-term-source-code-archive/
