### ISSUE TITLE
Banner mementos return 200 for everything

### ISSUE THREAD

**Issue by ibnesayeed** [webrecorder/pywb#549]
Banner mementos blindly echo back requested datetime in `Memento-Datetime` header with `200` status code irrespective of the existence of an exactly matching memento or no mementos at all.

See: https://ws-dl.blogspot.com/2020/03/2020-03-26-memento-compliance-audit-of.html#1-4-timegate

**Comment by ikreymer** [comment]
This should be fixed in pywb 2.4 release
