### ISSUE TITLE
Support both 200 and 302 style TimeGate simultaneously

### ISSUE THREAD

**Issue by ibnesayeed** [webrecorder/pywb#554]
Expose both styles of content negotiation (i.e., `200` and `302`) simultaneously, so that user-agents get to decide which one to consume, not the web master.

See: https://ws-dl.blogspot.com/2020/03/2020-03-26-memento-compliance-audit-of.html#3-4-timegate

**Comment by ikreymer** [comment]
I think this would further complicate the (already complex) logic surrounding memento lookup in pywb.
The 302 mode is used when redirection is on.
The 200 mode is used with redirection is off.
The memento mode mimics the configured replay mode.
