### ISSUE TITLE
query.html references missing url-polyfill.min.js file

### ISSUE THREAD

**Issue by anjackson** [webrecorder/pywb#571]
## Describe the bug
The query template references a static file that does not exist.

## Steps to reproduce the bug
If you go to pywb e.g. https://beta.webarchive.org.uk/wayback/archive/*/https://www.bbc.co.uk/  and open the console you'll see 

```
SyntaxError: expected expression, got '<' url-polyfill.min.js:1
```

## Expected behavior
No console errors.

**Comment by ikreymer** [comment]
Fixed in 2.4.2
