### ISSUE TITLE
pywb doesn't verify certificates

### ISSUE THREAD

**Issue by Lukey3332** [webrecorder/pywb#594]
## Describe the bug
Hello,
I am trying out pywb and it seems that it doesn't check ssl certificates for validity.

## Steps to reproduce the bug
Visit the following site in proxy recording mode, from the live collection, or by recording it.
https://badssl.com/dashboard/
Almost all tests show up as red.

## Expected behavior
The tests should show up as green instead, by failing the requests to to the hosts with invalid certificates.

## Environment
- OS: debian buster
- Browser: Firefox
- Version: 83.0

**Comment by JustAnotherArchivist** [comment]
I'd just like to point out that it is often necessary to archive websites that are no longer properly maintained, and that may include being served invalid certificates. So on my archiving activities (automated, not pywb-based), I almost always disable the validation. Whether this applies to pywb, I'm not sure.

**Comment by ikreymer** [comment]
Yes, that's correct, pywb does not validate certs for similar reason, although perhaps there should be an option to enable validation..
