### ISSUE TITLE
How to always rewrite things with https, not http

### ISSUE THREAD

**Issue by BinBashBanana** [webrecorder/pywb#615]
## Is your feature request related to a problem? Please describe.
Here is the problem: Replayed pages are messed up when viewed on custom domains connected to heroku (the host I am using), over https, using cloudflare. Heroku does not support SSL connections between cloudflare and itself, so I must turn that off. (Otherwise there is an error 525) But SSL can still be achieved between the client and cloudflare.

I believe what is going on here is that the pywb app sees the client as using http, even though they are using https, thus causing the page content to be rewritten with everything as http.

## Describe the solution you'd like
Would this solution work? Just treat the http connection as though it were https, and then rewrite the content with https.

What code would I have to change in order to fix this?

## Describe alternatives you've considered
I haven't considered any alternatives... I wouldn't know of any other way to fix this problem.

## Additional context
A video page on youtube, that won't load completely.
![A video page on youtube, that won't load completely.](https://user-images.githubusercontent.com/51469593/107110924-9b510900-6800-11eb-9abc-546f619fa4be.png)

**Comment by bricas** [comment]
I had a similar issue when pywb didn't originally respect forwarded protocol information, so a config option was introduced:
`force_scheme: https`

pywb was fixed to respect x-forwarded-proto so I don't need that option for my setup, but as as far as i know this is still available to use.

**Comment by BinBashBanana** [comment]
Does `force_scheme: https` go in the base area in config.yaml or does it go in the collection-specific area?

**Comment by bricas** [comment]
It was in my base config.yaml.

just to reiterate: this solution is more of a hack than anything, and if you can get `X-Forwarded-Proto` sent along to pywb, that's your BEST solution.

**Comment by BinBashBanana** [comment]
Would this work, if I put this in .htaccess? `header set X-Forwarded-Proto https`

**Comment by BinBashBanana** [comment]
Somehow that didn't work for me, but this did:  
Go to line 307 in `pywb/apps/rewriterapp.py`  
and replace it with `proto = "https"`
