### ISSUE TITLE
Recent versions of PYWB unable to replay coronavirus.data.gov.uk captures.

### ISSUE THREAD

**Issue by michaeltobin27** [webrecorder/pywb#639]
## Expected behavior
Pages underneath home page should load and display charts.

## What actually happened
On all pages which are not the home page, an error is displayed: 'Something went wrong'
e.g. if you go to coronavirus.data.gov.uk and click on the 'vaccinations' sub-category it will display this error.

## Access
I am accessing via Chrome and have tried Edge. It also will not replay when the WARC is replayed with conifer. 
This seems to be the case for all recent versions of PYWB but it replays fine on older versions, e.g. https://webarchive.nationalarchives.gov.uk/20210403000043/https://coronavirus.data.gov.uk/details/vaccinations

contact me for any more information:
michael[dot]tobin[at]nationalarchives.gov.uk

**Comment by ikreymer** [comment]
Thanks for re

**Comment by ikreymer** [comment]
Should be fixed now in 2.6.0b0 release if pywb is upgraded to that version.

**Comment by michaeltobin27** [comment]
Thanks for looking into this.
