### ISSUE TITLE
How to connect to a local proxy port which is already occupied

### ISSUE THREAD

**Issue by Abshan** [webrecorder/pywb#641]
My machine doesn't have an Internet connection, So I currently access the internet through an SSH tunnel. I'm running a proxy server on my machine, which I'm mapping the remote machine port to the local machine port. Since the port is already occupied by the proxy server, I can't seem to run pywb. Is there a method to archive the requests sent through my local proxy port?

OS: Rhel 7.9

**Comment by Lukey3332** [comment]
Hi, you can use a socks proxy, see https://pywb.readthedocs.io/en/latest/manual/configuring.html#socks-proxy-for-live-web
