### ISSUE TITLE
Mention installing extra requirement if using localization?

### ISSUE THREAD

**Issue by ldko** [webrecorder/pywb#648]
Because I didn't have translate-toolkit installed, I got this error when trying to make use of the new localization features:
```
$ wb-manager i18n extract es
Error: No module named 'translate'
```
I see translate_toolkit was added to the extra_requirements.txt which is used by travis, docker, and tox, but since the extra requirements aren't installed by default otherwise, should it be mentioned in the localization docs to install this? or is it mentioned somewhere that I missed? Thanks!

**Comment by ikreymer** [comment]
Added support for installing any extra i18n dependencies as extras via `pip install pywb[i18n]`, now mentioned in https://pywb.readthedocs.io/en/latest/manual/localization.html
Fixed in 2.6.0b1
