### ISSUE TITLE
eval rewriting breaks JS that defines object fields named 'eval'

### ISSUE THREAD

**Issue by ato** [webrecorder/pywb#663]
## Describe the bug

The JavaScript rewrite rules break code that uses "eval" as the name of an object field or method. The [less.js 1.3.0](https://github.com/less/less.js/blob/v1.3.0/lib/less/tree/rule.js#L39) library uses this pattern frequently as it defines many functions named 'eval'  to evaluate the parsed less syntax tree using a pattern like this:

```
      tree.Assignment.prototype = {
        eval: function (a) {
          ...
        }
      }
```

## Steps to reproduce the bug
```
$ cat >test.html <<EOF
<script>
obj = {
  eval: function() { return "OK"; }
};
document.write(obj.eval());
</script>
EOF
$ warcit -o http://example.org/ test.htm
$ wb-manager add test test.html.warc.gz
$ pywb
$ firefox http://localhost:8080/test/2/http://example.org/test.html
```
Correct output: `OK`
Incorrect output: (blank)

An in the wild example of a web page using less-1.3.0.min.js is <https://www.pipenetworks.com/>. Under pywb the page loads without any styles. With the eval rewrites in `regex_rewriters.py` commented out the page loads correctly.

## Expected behavior

While fixing all the eval false positives is probably impractical we could adjust the regex with lookahead/lookbehind assertions to prevent matching `eval:` and `obj.eval()`. That'll of course introduce a false-negative `(true?eval:null)("1+2")` but a construction like that is pretty contrived and hopefully very unlikely to appear in real code.

## Screenshots
N/A

## Environment
pywb 2.5.0
Firefox
Linux

**Comment by ikreymer** [comment]
The pywb 2.6 release (via #668) should fix, as much as possible w/o full parsing.
