### ISSUE TITLE
Recursively crawling a page with pywb recorder

### ISSUE THREAD

**Issue by TowardMyth** [webrecorder/pywb#665]
Hi there.

According to this [documentation](https://pywb.readthedocs.io/en/latest/manual/usage.html#using-pywb-recorder), I can use pywb recorder to record one webpage, by visiting `http://localhost:8080/my-web-archive/record/<url>`.

Is there a way to use pywb recorder to recursively record all pages on a particular domain?  For example, recording all pages on https://simplewebtool.com/. 

Thanks!

**Comment by ikreymer** [comment]
Yes, we have a separate tool, [Browsertrix Crawler](https://github.com/webrecorder/browsertrix-crawler) that can do this and has lots of other options. It uses pywb under the hood to do the capture, and is available as a docker image.
See the readme there for all the options.
