### ISSUE TITLE
i18n support does not work out of the box

### ISSUE THREAD

**Issue by vitezg** [webrecorder/pywb#674]
## Describe the bug
Following the steps in https://pywb.readthedocs.io/en/latest/manual/localization.html fails with 
```
Error: [Errno 2] No such file or directory: 'babel.ini'
```

## Steps to reproduce the bug
Follow the steps in the localization documentation as root:
```
pip3 install 'pywb'
[no error reported]
pip3 install 'pywb[i18n]'
[no error reported]
wb-manager i18n extract hu
Error: [Errno 2] No such file or directory: 'babel.ini'
```

## Expected behavior
The files for localization should get extracted by wb-manager without an error.

## Screenshots
![screenshot0](https://user-images.githubusercontent.com/745368/136176421-7619f1f1-b5b1-43ba-ba3f-ebe6f2c34970.png)
![screenshot1](https://user-images.githubusercontent.com/745368/136176430-b1a8d402-4d59-428b-9c76-3fb71630a444.png)
![screenshot2](https://user-images.githubusercontent.com/745368/136176434-dc228839-1edf-4247-870e-1be5d1b4fbfe.png)

## Environment
OS: Debian 10.9
Python: 3.7.3
Pywb: 2.6.0

## Additional context
After installing pywb no babel.ini file is found, not even using ```find /usr/local -name babel.ini ``` .

**Comment by ikreymer** [comment]
Unfortunately, to use the localization features, it is currently necessary to install from source, eg. cloning the repo and then running pywb from the repo directory. This is because the localization will need to be applied on the existing templates.
Will see if it is possible to support it with install from pip as well..

**Comment by vitezg** [comment]
Running pywb from the source directory seems to work, thanks a lot!
