### ISSUE TITLE
Issues with discord.com

### ISSUE THREAD

**Issue by DUOLabs333** [webrecorder/pywb#678]
## Describe the bug
I'm running `http://localhost:8080/live/https://discord.com/`, and it loads. I then want to click on `Login`. However, when I hover over it, it shows `http://localhost:8080/live///discord.com/login`. Going to `http://localhost:8080/live/https://discord.com/login` just gives a white screen (I'm already logged in, so it probably can't reach the cookie). Going to `http://localhost:8080/live/https://discord.com/login` in a Private Window gives the login screen, but the QR code never shows up.

## Expected behavior
I can use Discord as normal

## Environment

- OS: Linux
- Browser: Firefox
- Version: 2.6.0

**Comment by ikreymer** [comment]
I believe discord requires websockets to work, and there's not currently a way to archive and replay websocket traffic..

**Comment by pirate** [comment]
HAR files support websocket traffic saving 🙏 maybe this can be done someday https://playwright.dev/docs/next/network#replaying-from-har
