### ISSUE TITLE
wombat hooks for missing video

### ISSUE THREAD

**Issue by despens** [webrecorder/pywb#68]
Sometimes embedded videos supported by the yt-dl library are not available for various reasons at the time of archiving: video deleted, copyright violation, user closed their account, and so forth.

If a native video player is not supported at archiving time and a reason is known why the archiving failed, provide javascript hooks in wombat to handle those.

If the native video player can be archived and already shows the reason, this is not required.

**Comment by ikreymer** [comment]
This is mostly obsolete now that most video is HTML5 based. Re-open if you have any specific thoughts/use cases.
