### ISSUE TITLE
The URLs of static resources are broken

### ISSUE THREAD

**Issue by taicaile** [webrecorder/pywb#681]
![image](https://user-images.githubusercontent.com/23215696/141598330-17bc452b-c6bf-4f08-9266-9337e211340e.png)

Hello, the URLs for CSS/JS seem not working.

```bash
wb-manager init com
wayback --record --live -a --auto-interval 10
```
The above code is how I run it, not sure if I missed something.

**Comment by ikreymer** [comment]
Sorry, this was a regression in 2.6.1 :( Will have a fix shortly.
