### ISSUE TITLE
Wrong month number in new Vue calendar

### ISSUE THREAD

**Issue by Alseenrodelap** [webrecorder/pywb#718]
## Describe the bug
In 2.7 beta with the new Vue calendar activated, when viewing a collection > url search result you see the calendar view. When selecting a date you get a list of captures on that day. On the top, for may 10 (5th month) it says: 12-06-2022.

Note the 6. Somebody was really sleeping, may is the 5th month.

This is also happening when zooming in to the timeline on the top of the page.

## Steps to reproduce the bug
Install Pywb 2.7 beta and activate the Vue uit with:

ui:
  vue_calendar_ui: true

## Expected behavior
Correct month numbers.

## Screenshots
See screenshot. Note: I have the NL localization so in my screenshot the date is  7-6-2022 but should be 7-5-2022.
![screenshot-date](https://user-images.githubusercontent.com/33641101/168011406-8f1de4b2-3de2-45df-b760-e142edab45c8.jpg)

## Environment

- OS: Ubuntu 20.02
- Pywb 2.7 beta
- Browser: Safari

**Comment by tw4l** [comment]
This is fixed in released 2.7
