### ISSUE TITLE
HTTP 404 messages

### ISSUE THREAD

**Issue by edsu** [webrecorder/pywb#720]
When a snapshot is requested and a suitable record is not found in the collection why not respond with a 404 message instead of 200 OK?

## Describe the solution you'd like

If a request is made for something that doesn't exist a 404 message is returned. For example:

```
curl -i 'http://localhost:8080/public/20220516195853/https://webrecorder.net/does-not-exist'

HTTP/1.1 404 Not Found
Server: nginx/1.21.6
Date: Mon, 16 May 2022 22:28:48 GMT
Content-Type: text/html
Content-Length: 1518
Connection: keep-alive
Memento-Datetime: Mon, 16 May 2022 19:58:53 GMT
Link: <https://webrecorder.net/does-not-exist>; rel="original", <http://localhost:8080/public/https://webrecorder.net/does-not-exist>; rel="timegate", <http://localhost:8080/public/timemap/link/https://webrecorder.net/does-not-exist>; rel="timemap"; type="application/link-format", <http://localhost:8080/public/20220516195853mp_/https://webrecorder.net/does-not-exist>; rel="memento"; datetime="Mon, 16 May 2022 19:58:53 GMT"

<!DOCTYPE html>
<html>
<head>
<style>
html, body
{
  height: 100%;
  margin: 0px;
  padding: 0px;
...
```

## Additional context

I think this is useful for utilities that are checking the contents of a pywb collection instead of needing to do a regex on the response?

**Comment by edsu** [comment]
Looking closer at the HTML that's returned I can see that it's just a shell that contains some JavaScript for creating an iframe that contains the content. So it is not aware of whether it will result in an index hit or miss.

**Comment by anjackson** [comment]
We use the Memento TimeGate for checking things, such that in your case `http://localhost:8080/public/https://webrecorder.net/does-not-exist` should return a 404.

But, I agree that this is a confusing aspect of the system, and I think perhaps the playback page _should_ behave like the TimeGate.

**Comment by notevenaperson** [comment]
> We use the Memento TimeGate for checking things, such that in your case `http://localhost:8080/public/https://webrecorder.net/does-not-exist` should return a 404.

No it doesn't.
`curl -L "http://localhost:8080/my-web-archive/https://webrecorder.net/does-not-exist" --write-out %{http_code}` -> 200

I made a more detailed issue for this: #843
