### ISSUE TITLE
Issues deploying via uwsgi

### ISSUE THREAD

**Issue by despens** [webrecorder/pywb#769]
## Describe the bug
When deploying via uwsgi using the provided uwsgi.ini, requests to web archive replay URLs time out and make the whole pywb process hang indefinitely. Request to template rendering URLs work.

## Steps to reproduce the bug
- Start up fresh system with Ubuntu 20.04 or 22.04
- `sudo apt install uwsgi uwsgi-plugin-python3 python3-pip httpie`
- `sudo pip3 install pywb`
- `uwsgi uwsgi.ini`
- `http localhost:8080` — works, as does any other page that just renders a template
- `http localhost:8080/collection/2022/example.com/` — process hangs, reuqests timing out

## Expected behavior
Web archives should render

## Environment
Tested configurations that expose this error:
| OS | uwsgi version | python version | pywb version
|----|-------|-----|----|
| Ubuntu 22.04 | 2.0.20-debian | 3.10.6 | 2.6.8
| Ubuntu 20.04 | 2.0.18-debian | 3.8.10 | 2.6.8
| Ubuntu 18.04 | 2.0.15-debian | 3.6.9 | 2.6.8
| Ubuntu 22.04 | 2.0.20-debian | 3.10.6 | 2.6.7

## Additional context
- Had to add `plugins = python3` to uwsgi.ini for requests to be handled in the first place
- using nginx with `uwsgi_pass localhost:8081` leads to the same results
- When running `pywb` or `wayback` without uwsgi, everything works fine
- Requests to template rendering URLs emit log lines, requests to web archive replay URLs do not emit any log lines

**Comment by despens** [comment]
The following combination works:

| OS | uwsgi version | python version | pywb version
|-----|-------------------|----------------------|------------------
| Ubuntu 20.04 | 2.0.20 | 3.8.10 | 2.6.8

```
sudo apt install python3-pip
sudo pip3 install uwsgi
sudo pip3 install pywb
```

Apparently, uwsgi doesn't yet work well with Python > 3.8 although this was [announced for version 2.0.20](https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.20.html). On systems with Python 3.10.x, uwsgi is not possible to install via pip, and the debian-provided uwsgi binary package seems to have its own issues.

Unless uwsgi works smoothly with Python 3.10.x perhaps it would make sense to update the pywb documentation to mention that an environment with Python 3.8.x is recommended. For Ubuntu users that would be Ubuntu 20.04.

**Comment by tw4l** [comment]
Note as well that it's necessary to `pip install wheel` prior to installing via `pip install uwsgi` - otherwise `uwsgi` will try to install via the legacy `setup.py uwsgi`, which appears to throw an error.

**Comment by tw4l** [comment]
Verified that I'm seeing the same behaviour as @despens when installing uwsgi (via `apt` or `pip`) in Ubuntu 22.04 with Python 3.10 and uwsgi 2.0.20. However, using a Python virtual environment as per https://github.com/webrecorder/pywb/issues/769#issuecomment-1302291642 resolves the issue, and does not require any modifications to `uwsgi.ini`.

I've also verified that running pywb via `wayback` does not have the same issue - it only occurs when invoking/running the application with `uwsgi` directly.

I think the simplest course of action here is to recommend use of virtual environments when running pwyb via `uwsgi` directly, which is a good practice anyway in terms of dependency isolation.

**Comment by tw4l** [comment]
Since the pywb documentation recommends running the server with the `wayback` command or Docker, I'm not sure if a documentation update is needed or if the information in this issue will suffice for users running into the same problem. @ikreymer, do you have thoughts?

**Comment by tw4l** [comment]
Ah, I missed the nginx configuration example in the pywb docs. Use of a virtualenv is [supported in uwsgi via the -H flag](https://uwsgi-docs.readthedocs.io/en/latest/Python.html#virtualenv-support), so using one shouldn't require any tweaks to the `nginx.conf`.

**Comment by despens** [comment]
Thanks for confirming and noting the need to install `wheel`.
Using a venv is nice but makes it hard to use the wb-manager commands. (If I am understanding correctly that both uwsgi and pywb would need to be installed in the same venv?)

**Comment by tw4l** [comment]
Hm, that's a good point. I believe pywb can be installed outside of the virtualenv, but it might need some testing.
