### ISSUE TITLE
[2.7.0] Template issues and clarifications

### ISSUE THREAD

**Issue by bricas** [webrecorder/pywb#778]
Since upgrading from 2.6.9 to 2.7.0 I've had to redo my template overrides to match the new style.

Looking at the documentation, the first part mentions base.html:

> Base Templates (and supporting templates)
> File: base.html
> 
> This template includes the HTML added to all other pages, replay and non-replay. 

What is meant by "all *other* pages" -- this is the first instance of pages being mentioned, so would be make more sense to write it as "all pages"?

Assuming this means "all pages", I've added my analytics code to `head.html` which is the recommended in the documentation.

However, when viewing an archived page, I don't see the analytics code anywhere. In the documentation i see:

> Top Frame Template
> File: frame_insert.html
> 
> This template represents the top-level frame that is inserted to render the replay in framed mode.
> 
> By design, this template does not extend from the base template.

So, is the the template that is used to view an archived page? Do i need to add my analytics code to that file as well?

Also, I'm no longer seeing page titles (a `<title>` tag for the page) when viewing archived pages. Is this no longer supported?

Thanks in advance for the help.

**Comment by tw4l** [comment]
Hi @bricas, thanks for the issue! I'll have a look at the Template Guide based on your comments here and make some edits to help clarify. Thank you for pointing out some outdated comments in the `base.html` section.

In terms of your immediate questions, yes, the `frame_insert.html` template is what's used to view an archived page in the default framed mode (it's mostly the banner and iframe), and if you want to track behaviours on those pages you'd have to add your analytics code to that template in addition to `head.html`.

The `<title>` tag should still be there! That's used as the source for the title in the banner. You might have to look for the `<head>` element inside the replay iframe to find it.

**Comment by bricas** [comment]
Thanks @tw4l, I've added my code to that template it and shows as expected.

WRT to `title`, the old behaviour would dynamically push the title from replay frame to the outer frame -- i did some googling around and found this example: http://webadmin.oszk.hu/pywb/20220929105640/https://konyvtarak.hu/

**Comment by tw4l** [comment]
Thanks @bricas - looks like this is a regression in the 2.7.0 release that wasn't caught in beta testing. We'll scope it in for a 2.7.1 patch release along with any other issues that come up in the first days of the release being out in the world.

**Comment by bricas** [comment]
Excellent, thank you!

**Comment by tw4l** [comment]
Hi @bricas - I've pushed a commit in the [2.7.1-dev](https://github.com/webrecorder/pywb/tree/2.7.1-dev) branch to fix the title issue if you'd like to test. We will include this in the point release - just working on a few other issues to include in that release as well :)

**Comment by tw4l** [comment]
The 2.7.1 documentation (will be published with release) has been updated to accurately describe the current state of the pywb templates and specifically mention that analytics code, etc. meant to be included in framed replay should also be added to `frame_insert.html`.

**Comment by bricas** [comment]
Thank you for addressing these issues. Cheers.
