### ISSUE TITLE
Replay fails (looks like a rewriting issue): Error setting href = index.cfm?tem=2&spr=0&hpn=1&idn=999999

### ISSUE THREAD

**Issue by steph-nb** [webrecorder/pywb#789]
## Expected behavior
Replay of https://manimatter.ch/ should work without a problem. This URL should be loaded and displayed:
https://manimatter.ch/index.cfm?tem=2&spr=0&hpn=1&idn=999999

## What actually happened
1. Load attached warc.gz in pywb
2.  go to: https://manimatter.ch/
3. The Replay always restarts, leading to a flickering effect.

In the Browser-Console I can find this error:
Error setting href = index.cfm?tem=2&spr=0&hpn=1&idn=999999

By the way, when uploaded to conifer, Replay works just fine.

## Browser
- OS: Windows 10
- Browser chrome 100
- pywb: 2.6.9 / 2.7.2

**Comment by ikreymer** [comment]
This was due to an issue with relative URLs not resolving correctly when the site assigns to window.location, have a fix for this in wombat.js, which will make it into the next release!

**Comment by steph-nb** [comment]
Many thanks Ilya!
