### ISSUE TITLE
Logo href in Vue is hardcoded to "/"

### ISSUE THREAD

**Issue by maeb** [webrecorder/pywb#790]
https://github.com/webrecorder/pywb/blob/3c94da04a2dd0ba270652493d477ea474b4fe551/pywb/vueui/src/App.vue#L7

If pywb is configured to run from a prefix the link will be wrong.

**Comment by tw4l** [comment]
Thanks @maeb and good catch!

**Comment by tw4l** [comment]
I'm tempted to remove the link from the navbar logo altogether, as many production instances don't their collections page publicly visible. Would that work for you @maeb ? Or as an alternative we could possibly have the home URL set via `config.yaml` and simply skip the link if a value isn't set? @ikreymer - thoughts?

**Comment by ikreymer** [comment]
I like the idea of making it configurable? Some do have a collections page, but at a different URL potentially?

**Comment by tw4l** [comment]
Linked PR adds a `ui.logo_home_url` option to `config.yaml`. If set, it will be set as the href for the logo, otherwise the logo won't link anywhere.

**Comment by tw4l** [comment]
Merged and to be included in 2.7.3
