### ISSUE TITLE
On indexing exception with warcio, auto indexing is terminated

### ISSUE THREAD

**Issue by oskarhek** [webrecorder/pywb#792]
## Describe the bug
When a warc is provided wich causes warcio to throw an exception, auto indexing is terminated.

## Steps to reproduce the bug
when wayback is autoindexing put the enclosed warc in the archive folder.
the error you get: 
warcio.statusandheaders.StatusAndHeadersParserException: Expected Status Line starting with ['WARC/1.1', 'WARC/1.0', 'WARC/0.17', 'WARC/0.18'] - Found: WARC-Type: request

[9df7a85a-bce2-4d39-9e42-bcd44c5bb7c6.warc.zip](https://github.com/webrecorder/pywb/files/10336498/9df7a85a-bce2-4d39-9e42-bcd44c5bb7c6.warc.zip)

## Expected behavior
Log the error, and continue auto indexing.

## Environment
Running pywb 2.7.3 in a docker environment

**Comment by tw4l** [comment]
Fix merged and to be included in 2.7.3
