### ISSUE TITLE
Add WACZ archives to collections

### ISSUE THREAD

**Issue by kuechensofa** [webrecorder/pywb#799]
## Is your feature request related to a problem? Please describe.

When receiving a web archive in WACZ format it currently isn't possible to add it to a collection using `wb-manager`.

## Describe the solution you'd like

It should be possible to use `wb-manager add COLLECTION WACZ-FILE` to add the contents of a WACZ archive to a collection. `wb-manager` should unpack the WARC files of the archive and the indexes to a temporary directory, move the extracted WARC files to the collection and then add the WACZ indices to the collection index.

## Describe alternatives you've considered

Currently it is possible to add the contents of a WACZ archive to a collection by unpacking the WACZ archive and manually adding its contents but it's a very manual process.

**Comment by tw4l** [comment]
Hi @kuechensofa , sorry it took so long but this is finally being released in pywb 2.8.0 today! We've renamed the argument to `wb-manager add --unpack-wacz` but otherwise it's the same :) We're not planning WACZ support without unpacking in 2.9.

Thanks so much for this great contribution!
