### ISSUE TITLE
Default Localisation misses on date format

### ISSUE THREAD

**Issue by oskarhek** [webrecorder/pywb#804]
## Describe the bug
Default language is not used for formatting dates 

## Steps to reproduce the bug
for me the default language is set to NL
In the calendar when I select a date I still get the American notation with starts with a month.
after I select the nl language, it is transformed to day/month/year.

## Expected behavior
to see the correct format immediately (day/month/year)

![correct](https://user-images.githubusercontent.com/53567709/215757030-2b732df2-5247-45af-82a3-f190d3d43fc8.png)
![wrong](https://user-images.githubusercontent.com/53567709/215757041-e7a88700-e665-4c07-97c4-bf582fd91756.png)

**Comment by krakan** [comment]
Yes, that is indeed the intended behavior. As I wrote this piece of code I'll have another go at getting it right but unfortunately "it works for me" ... :disappointed:

Update: Oh dear! I found the error - I've previously detected the issue and cheated in solving it meaning to fix it later and then promptly forgotten about it. The default language is indeed used - but only if it's Swedish. :blush:

**Comment by oskarhek** [comment]
Can see if I can convince people to serve our pages in Swedish :)

**Comment by tw4l** [comment]
Confirmed #805 resolves the issue - with default set to French and no language in request, calendar date is displaying DD/MM/YYYY as expected. Thanks both!
