### ISSUE TITLE
New timeline interface breaks old timeline URLs like COL/*/URL

### ISSUE THREAD

**Issue by anjackson** [webrecorder/pywb#807]
## Describe the bug

We often use URLs like `COL/*/URL` to point people to the pure timeline overview of an URL. e.g.

https://www.webarchive.org.uk/wayback/archive/*/http://portico.bl.uk/

Using the new banner/timeline in 2.7, this URL no longer works and shows as "0 captures". The new version only supports URLs like:

https://dev.webarchive.org.uk/wayback/en/archive/*?url=https%3A%2F%2Fportico.bl.uk

## Steps to reproduce the bug

Upgrade to 2.7.x, and attempt to visit the calendar page using URLs like `PREFIX/COLLECTION/*/URL`

## Expected behavior

Should show the calendar view, either via a redirect or directly.

**Comment by ikreymer** [comment]
The standard `COL/*/URL` should work general (eg. `localhost:8080/pywb/*/example.com/`) should be working (and there's various tests for that), but i wonder if its something specific to the prefix or the ukwa-pywb setup that's breaking it in this case..

**Comment by tw4l** [comment]
This particular issue was a faulty template in the ukwa-pywb repo.

**Comment by tw4l** [comment]
Unrelated cause (what timing) but commit https://github.com/webrecorder/pywb/commit/59d9beac057143d906d3b778088168225c6fc7e0 also seems to cause a failure fetching CDX when COL/*/URL when running via gunicorn or uwsgi. COL/*/URL works as expected when running pywb via `wayback` however.
