### ISSUE TITLE
ACL support for timestamp & date range

### ISSUE THREAD

**Issue by VascoRatoFCCN** [webrecorder/pywb#825]
We would like to be able to specify timestamps or date ranges on the `.aclj` file. The [documentation](https://pywb.readthedocs.io/en/docs/manual/access-control.html) already suggests that this feature will eventually be implemented:  

> The prefix consists of a SURT key and a `-` (currently reserved for a timestamp/date range field to be added later).

We require this feature to answer removal requests, which often only implies blacklisting a SURT for a specific timestamp or a small date range.

**Comment by edsu** [comment]
I think this is functionally similar to #703?

**Comment by VascoRatoFCCN** [comment]
You're right, it's a duplicate. I'll close this one!
