### ISSUE TITLE
pywb users and developers survey to inform future development roadmap

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/pywb#842]
We've created up a survey to better understand how folks are using pywb, to better plan for future development roadmap as well as understand who else may be interested in contributing to the core project.
If you have a moment, please fill it out here: https://docs.google.com/forms/d/e/1FAIpQLSc0OhPwnolXN3QyWgg1IglF25kx4Es5IV9fH9oMsBtsg_sLbQ/viewform

**Comment by tw4l** [comment]
Plan for perhaps August

**Comment by Shrinks99** [comment]
Make When2meet for this!
