### ISSUE TITLE
Seeking Guidance: Efficiently Managing Large-Scale WARC Files and Optimizing Indexing

### ISSUE THREAD

**Issue by ShanePark** [webrecorder/pywb#858]
Hello there! :)

First of all, I want to express my gratitude for your excellent work, which has allowed me to handle numerous warc files with ease.

I have a question regarding my current setup. 

I am dealing with over 30,000 warc files, totaling about 10+ TB in size. Initially, I added them all to a single collection. However, as the total size of the warc files exceeded 4TB, indexing started to take an extremely long time. Even when I try to add a small 1MB file using 'wb-manager add,' it takes over a minute to complete the process. Additionally, the 'index.cdxj' file itself has grown to over 4GB in size.

To address this issue, I decided to divide the warc files into 256 collections. This approach has improved the indexing speed compared to the single collection setup. However, the 'index.cdxj' files for each collection are becoming larger and larger over time. Moreover, I find myself needing to delete some warc files that are no longer necessary. Therefore, having such large 'index.cdxj' files is not ideal for my requirements.

I've considered using 'wb-manager reindex' to address this, but due to the large number of warc files, it takes really long time and I want to ensure that I can still have playback functionality for the existing warcs while adding new ones.

My main questions are:

1. Is there a limit to the number of collections I can have? Would it be feasible to create individual collections for each of the 30,000+ warc files? Are there any potential problems with this approach?

2. If creating individual collections for each warc file is not feasible or recommended, do you have any suggestions for reindexing (removing deleted warcs) while still maintaining the playback functionality?

I came across the "Auto-Indexing Mode" in the tutorial, but it mentions that it doesn't support deletion.

Thank you for your assistance!

**Comment by lasztoth** [comment]
Hi,

Perhaps in this case it would make sense to use an index server instead of .cdxj files? An often recommended solution is to use OutbackCDX (https://github.com/nla/outbackcdx) with PyWb.

Kind regards

**Comment by ShanePark** [comment]
Thanks, I'll git it a try
